spring:
  application:
    name: finalProject20110451
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/cnpmmProject

jwt:
  secret: tranvandan20110451tranvandan20110451tranvandan20110451
